biotope/biotope-element

- index.ts
Food for thought:
We should make the BioElement class abstract since we're not planning on using it directly
> Added abstract to BioElement class

- tsconfig.json
My idea was to organise the tsconfig.json better, from module definition, to ts-rules and then compilation paths.
> Better organisation on tsconfig.json

- package-lock.json
- package.json
- src/attribute-name.ts
- src/index.ts
- src/is-registered.ts
- src/types.ts
- tsconfig.json
Split code into more testable modules
> Task: Code splitting

- .gitignore
- docs/01-introduction.mdx
- doczrc.js
- netlify.toml
- package.json
- yarn.lock
Preview for now can be found under: https://biotope-element.netlify.com/
> add docz 🚋

- .gitignore
- package.json
- src/host.mixin.scss
- src/index.ts
- tests/attributeChangedCallback.spec.ts
- tests/dependencies.spec.ts
- tests/help.js
- tests/mocha.opts
- tests/props.spec.ts
- tsconfig.json
- yarn.lock
Adding mocha and chai and some unit tests
> Add unit tests

- package-lock.json
- package.json
- yarn.lock
> Fix copy task in build for windows

- docs/02-basics.mdx
- src/camelize.ts
- src/index.ts
- tests/attributeChangedCallback.spec.ts
> Hyphen attributes

- package-lock.json
- package.json
- yarn.lock
Currently some version higher then 2.13.0 is breaking our system.
So for now I fixed the version. We should upgrade soon (see #31 )
> Fix version to omit breaking change

- src/index.ts
> Allow props to be public

- jest.config.js
- package-lock.json
- package.json
- tests/attributeChangedCallback.spec.ts
- tests/dependencies.spec.ts
- tests/help.js
- tests/mocha.opts
- tests/props.spec.ts
- tests/rendering.spec.ts
- tests/setup.js
> Upgrade hyperhtml-element version

- example/package-lock.json
- example/src/button-js/button.html
- example/src/button-js/index.js
- example/src/index.html
- package-lock.json
> added example with button click alert

- docs/component.md
Since the documentation left me clueless for how to use booleans in the attributes, I created a little doc extension. 🤓
> Add approach for passing booleans with attributes

- docs/_sidebar.md
- docs/events.md
- example/package-lock.json
> docs: ✏️ Update events docs and add it to sidebar

- example/src/index.html
- example/src/ts/two-way-data-binding/index.html
- example/src/ts/two-way-data-binding/index.ts
- example/src/ts/two-way-data-binding/input.ts
> docs: ✏️ Add two way data binding example

- README.md
> docs: ✏️ Add polyfill notes to readme

- package-lock.json
- rollup.config.js
Build wasn't working anymore, because of `this` being undefined in global context. I changed that to be `null` and now the build runs again
> 🐛 fix: rollup config

- docs/_sidebar.md
- docs/guide-data-channels.md
> docs: ✏️ Add guide for data channels

- docs/_sidebar.md
- docs/lifecycle-hooks.md
> docs: ✏️ Add lifecycle callback docs

- docs/styling.md
> add ie11/edge style guidelines

- docs/advanced.md
> update event handling with biotope element

- .travis.yml
github actions config is already added to master
> remove travis in favor of github actions

- package-lock.json
- package.json
Fix `host.mixin.scss` not being copied to lib folder.
> Bugfix: Style mixin copy

- docs/advanced.md
- examples/src/js/element-refs/index.js
- examples/src/ts/element-refs/index.ts
- package-lock.json
- src/attribute-changed-callback.ts
- src/create-html.ts
- src/emit.ts
- src/get-component-name.ts
- src/index.ts
- src/internal-types.ts
- src/refs.ts
- src/register.ts
- src/types.ts
- tests/get-component-name.spec.ts
- tests/refs.spec.ts
LighterHTML already gives us a way to have refs
`createRef` and it's typing just makes it easier.
~*Still missing documentation*~
https://deploy-preview-177--biotope-element.netlify.com/#/advanced?id=references
> Feature: Refs

- .codecov.yml
Since we now have 100% code coverage, I'd suggest we try to keep it.
> Task: Readjust codecov

- package-lock.json
- package.json
- src/index.ts
- src/internal-types.ts
- src/register.ts
- tests/register.spec.ts
Resolves #174 by removing the feature as decided.
> Task: Remove basedon

- package-lock.json
- package.json
- src/create-html.ts
Since rollup packs everything for us, we can drop the dependency and prevent misuse of the component.
And one less package for people who install it ;)
> Feature: Zero dependencies

- docs/experimental.md
- website/i18n/en.json
- website/sidebars.json
Adds an `Experimental` section to our docs.
> Task: Experimental docs

- docs/component.md
> Task: Add partial render condition

- README.md
> Task: Update readme
